set echo on
CREATE OR REPLACE PROCEDURE "ZRUS_ALL_OBJEKTY_SCHEMATU" AS
-- pokud v logu bude uvedeno, ze nektery objekt nebyl zrusen, protoze na nej jiny jeste existujici objekt stavi,
-- spust proceduru opakovane, dokud se nezrusi vse
v_pom PLS_INTEGER;
BEGIN
LOOP
FOR irec IN (SELECT DISTINCT
                    object_type,object_name,
                    'drop '||object_type||' "'||object_name||'"'||
                    CASE object_type WHEN 'TABLE' THEN ' cascade constraints purge'
                                     ELSE ' '
                    END AS prikaz
              FROM user_objects
              WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU'
            )
  LOOP
   BEGIN
   DBMS_OUTPUT.put_line('prikaz '||irec.prikaz);
      EXECUTE IMMEDIATE irec.prikaz;
   EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.put('neni ');
   END;
   DBMS_OUTPUT.put_line('zrusen(a) '||irec.object_type||' '||irec.object_name);
  END LOOP;
SELECT COUNT(*) INTO v_pom
FROM user_objects
WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU';
EXIT WHEN v_pom = 0;
END LOOP;
DBMS_OUTPUT.put_line('hotovo!');
END ZRUS_ALL_OBJEKTY_SCHEMATU;
/
execute ZRUS_ALL_OBJEKTY_SCHEMATU

--------------------------------------------------------
--  File created - Monday-May-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BAND
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."BAND" 
   (	"NAME" CHAR(50 CHAR), 
	"STYLE" CHAR(50 CHAR), 
	"BIRTHDAY" DATE, 
	"DEATHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONCERT
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."CONCERT" 
   (	"DATETIME_START" DATE, 
	"DATETIME_END" DATE, 
	"NAME" CHAR(50 CHAR), 
	"TICKET_PRICE" NUMBER(*,0), 
	"PLACE_ADDRESS" CHAR(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ELECTRONIC
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."ELECTRONIC" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"SYNTHESIZER" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAN
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."FAN" 
   (	"FAN_ID" NUMBER(*,0), 
	"NAME" CHAR(30 CHAR), 
	"FAM_NAME" CHAR(30 CHAR), 
	"HAIR_COLOR" CHAR(10 CHAR), 
	"TATTOO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HAVING_FUN
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."HAVING_FUN" 
   (	"CONCERT_ADDRESS" CHAR(100 CHAR), 
	"CONCERT_DATETIME_START" DATE, 
	"FAN_FAN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IN_BAND
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."IN_BAND" 
   (	"BAND_NAME" CHAR(50 CHAR), 
	"MUSICIAN_FAN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IS_FAN
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."IS_FAN" 
   (	"FAN_FAN_ID" NUMBER(*,0), 
	"BAND_NAME" CHAR(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KEYBOARD
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."KEYBOARD" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"NUM_OF_OCTAVES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MIC
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."MIC" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUSICIAN
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."MUSICIAN" 
   (	"ROLE" CHAR(20 CHAR), 
	"FAN_FAN_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUS_INST
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."MUS_INST" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"INSTRUMENT_NAME" CHAR(30 CHAR), 
	"MUSICIAN_FAN_ID" NUMBER(*,0), 
	"INST_DESC_ID" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OTHER
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."OTHER" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"INSTRUMENT_NAME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERCUSSION
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."PERCUSSION" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"NEED_STICKS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFORMANCE
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."PERFORMANCE" 
   (	"CONCERT_ADDRESS" CHAR(100 CHAR), 
	"CONCERT_DATETIME_START" DATE, 
	"BAND_NAME" CHAR(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACE
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."PLACE" 
   (	"ADDRESS" CHAR(100 CHAR), 
	"PHONE_NUMBER" CHAR(20 CHAR), 
	"CAPACITY" NUMBER(*,0), 
	"NAME" CHAR(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SONG
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."SONG" 
   (	"SONG_NAME" VARCHAR2(50 CHAR), 
	"ALBUM" VARCHAR2(50 CHAR), 
	"YEAR" DATE, 
	"LENGTH" NUMBER(*,0), 
	"BAND_NAME" CHAR(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STRINGED
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."STRINGED" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"NUM_OF_STRINGS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WIND
--------------------------------------------------------

  CREATE TABLE "BABUSAND"."WIND" 
   (	"INSTRUMENT_INS_ID" NUMBER(*,0), 
	"RANGE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View ALL_FANS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BABUSAND"."ALL_FANS" ("NAME", "FAM_NAME", "BAND_NAME") AS 
  SELECT name, fam_name, band_name FROM FAN FULL OUTER JOIN IS_FAN ON FAN.FAN_ID = IS_FAN.FAN_FAN_ID;
--------------------------------------------------------
--  DDL for View PRICEUPDATE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BABUSAND"."PRICEUPDATE" ("DATETIME_START", "PLACE_ADDRESS", "TICKET_PRICE", "BANDS") AS 
  SELECT  DATETIME_START,
        PLACE_ADDRESS,
        TICKET_PRICE,
        BANDS
FROM 
  (SELECT CONCERT.DATETIME_START, 
          CONCERT.TICKET_PRICE,
          CONCERT.PLACE_ADDRESS
  FROM CONCERT
  WHERE name = 'WOA')
LEFT OUTER JOIN
        (SELECT datetime_start AS st, place_address AS pl, Bands
        FROM 
          (SELECT datetime_start, place_address, ticket_price, COUNT(*) AS Bands
          FROM CONCERT
          INNER JOIN PERFORMANCE
          ON datetime_start = concert_datetime_start
            AND CONCERT.PLACE_ADDRESS = PERFORMANCE.CONCERT_ADDRESS
          WHERE CONCERT.name = 'WOA'
          GROUP BY datetime_start, place_address, ticket_price))
ON st = DATETIME_START AND pl = PLACE_ADDRESS;
--------------------------------------------------------
--  DDL for View TATTOO_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BABUSAND"."TATTOO_VIEW" ("NAME", "FAM_NAME") AS 
  SELECT name, fam_name FROM FAN WHERE TATTOO = '1' ORDER BY name, fam_name;

 --------------------------------------------------------
--  DDL for Index HAVING_FUN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."HAVING_FUN_PK" ON "BABUSAND"."HAVING_FUN" ("FAN_FAN_ID", "CONCERT_ADDRESS", "CONCERT_DATETIME_START") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IN_BAND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."IN_BAND_PK" ON "BABUSAND"."IN_BAND" ("BAND_NAME", "MUSICIAN_FAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WIND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."WIND_PK" ON "BABUSAND"."WIND" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."SONG_PK" ON "BABUSAND"."SONG" ("BAND_NAME", "ALBUM", "SONG_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLACE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."PLACE_PK" ON "BABUSAND"."PLACE" ("ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STRINGED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."STRINGED_PK" ON "BABUSAND"."STRINGED" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."MIC_PK" ON "BABUSAND"."MIC" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IS_FAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."IS_FAN_PK" ON "BABUSAND"."IS_FAN" ("FAN_FAN_ID", "BAND_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUSICIAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."MUSICIAN_PK" ON "BABUSAND"."MUSICIAN" ("FAN_FAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KEYBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."KEYBOARD_PK" ON "BABUSAND"."KEYBOARD" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ELECTRONIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."ELECTRONIC_PK" ON "BABUSAND"."ELECTRONIC" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUS_INST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."MUS_INST_PK" ON "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BAND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."BAND_PK" ON "BABUSAND"."BAND" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERCUSSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."PERCUSSION_PK" ON "BABUSAND"."PERCUSSION" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERFORMANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."PERFORMANCE_PK" ON "BABUSAND"."PERFORMANCE" ("CONCERT_ADDRESS", "CONCERT_DATETIME_START", "BAND_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OTHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."OTHER_PK" ON "BABUSAND"."OTHER" ("INSTRUMENT_INS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."FAN_PK" ON "BABUSAND"."FAN" ("FAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONCERT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BABUSAND"."CONCERT_PK" ON "BABUSAND"."CONCERT" ("PLACE_ADDRESS", "DATETIME_START") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OTHER
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."OTHER" ADD CONSTRAINT "OTHER_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."OTHER" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."OTHER" MODIFY ("INSTRUMENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HAVING_FUN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."HAVING_FUN" ADD CONSTRAINT "HAVING_FUN_PK" PRIMARY KEY ("FAN_FAN_ID", "CONCERT_ADDRESS", "CONCERT_DATETIME_START")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."HAVING_FUN" MODIFY ("CONCERT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."HAVING_FUN" MODIFY ("CONCERT_DATETIME_START" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."HAVING_FUN" MODIFY ("FAN_FAN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFORMANCE
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."PERFORMANCE" ADD CONSTRAINT "PERFORMANCE_PK" PRIMARY KEY ("CONCERT_ADDRESS", "CONCERT_DATETIME_START", "BAND_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."PERFORMANCE" MODIFY ("CONCERT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."PERFORMANCE" MODIFY ("CONCERT_DATETIME_START" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."PERFORMANCE" MODIFY ("BAND_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MIC
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MIC" ADD CONSTRAINT "MIC_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."MIC" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."MIC" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WIND
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."WIND" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."WIND" MODIFY ("RANGE" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."WIND" ADD CONSTRAINT "WIND_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BAND
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."BAND" ADD CONSTRAINT "BAND_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."BAND" ADD CONSTRAINT "DATES_CHECK" CHECK (DEATHDAY IS NULL OR DEATHDAY > BIRTHDAY) ENABLE;
 
  ALTER TABLE "BABUSAND"."BAND" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."BAND" MODIFY ("STYLE" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."BAND" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IN_BAND
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."IN_BAND" ADD CONSTRAINT "IN_BAND_PK" PRIMARY KEY ("BAND_NAME", "MUSICIAN_FAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."IN_BAND" MODIFY ("BAND_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."IN_BAND" MODIFY ("MUSICIAN_FAN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KEYBOARD
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."KEYBOARD" ADD CONSTRAINT "KEYBOARD_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."KEYBOARD" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."KEYBOARD" MODIFY ("NUM_OF_OCTAVES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERCUSSION
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."PERCUSSION" ADD CONSTRAINT "PERCUSSION_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."PERCUSSION" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."PERCUSSION" MODIFY ("NEED_STICKS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUSICIAN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MUSICIAN" ADD CONSTRAINT "MUSICIAN_PK" PRIMARY KEY ("FAN_FAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."MUSICIAN" MODIFY ("ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."MUSICIAN" MODIFY ("FAN_FAN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUS_INST
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MUS_INST" ADD CONSTRAINT "MUS_INST_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."MUS_INST" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."MUS_INST" MODIFY ("MUSICIAN_FAN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."MUS_INST" MODIFY ("INST_DESC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLACE
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."PLACE" ADD CONSTRAINT "CAPACITY_CHK" CHECK (CAPACITY > 0) ENABLE;
 
  ALTER TABLE "BABUSAND"."PLACE" ADD CONSTRAINT "PLACE_PK" PRIMARY KEY ("ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."PLACE" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."PLACE" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."PLACE" MODIFY ("CAPACITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SONG
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."SONG" ADD CONSTRAINT "LEN_CHK" CHECK (LENGTH > 0) ENABLE;
 
  ALTER TABLE "BABUSAND"."SONG" ADD CONSTRAINT "SONG_PK" PRIMARY KEY ("BAND_NAME", "ALBUM", "SONG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."SONG" MODIFY ("SONG_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."SONG" MODIFY ("ALBUM" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."SONG" MODIFY ("YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."SONG" MODIFY ("LENGTH" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."SONG" MODIFY ("BAND_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FAN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."FAN" ADD CONSTRAINT "FAN_PK" PRIMARY KEY ("FAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."FAN" MODIFY ("FAN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."FAN" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."FAN" MODIFY ("FAM_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STRINGED
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."STRINGED" ADD CONSTRAINT "STRINGED_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."STRINGED" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."STRINGED" MODIFY ("NUM_OF_STRINGS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONCERT
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."CONCERT" ADD CONSTRAINT "BEG_END_CHK" CHECK (DATETIME_START <= DATETIME_END) ENABLE;
 
  ALTER TABLE "BABUSAND"."CONCERT" ADD CONSTRAINT "CONCERT_PK" PRIMARY KEY ("PLACE_ADDRESS", "DATETIME_START")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."CONCERT" ADD CONSTRAINT "PRICE_CHK" CHECK (TICKET_PRICE >= 0) ENABLE;
 
  ALTER TABLE "BABUSAND"."CONCERT" MODIFY ("DATETIME_START" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."CONCERT" MODIFY ("DATETIME_END" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."CONCERT" MODIFY ("TICKET_PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."CONCERT" MODIFY ("PLACE_ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_FAN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."IS_FAN" ADD CONSTRAINT "IS_FAN_PK" PRIMARY KEY ("FAN_FAN_ID", "BAND_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."IS_FAN" MODIFY ("FAN_FAN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."IS_FAN" MODIFY ("BAND_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECTRONIC
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."ELECTRONIC" ADD CONSTRAINT "ELECTRONIC_PK" PRIMARY KEY ("INSTRUMENT_INS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BABUSAND"."ELECTRONIC" MODIFY ("INSTRUMENT_INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BABUSAND"."ELECTRONIC" MODIFY ("SYNTHESIZER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONCERT
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."CONCERT" ADD CONSTRAINT "CONCERT_PLACE_FK" FOREIGN KEY ("PLACE_ADDRESS")
	  REFERENCES "BABUSAND"."PLACE" ("ADDRESS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ELECTRONIC
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."ELECTRONIC" ADD CONSTRAINT "ELECTRONIC_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HAVING_FUN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."HAVING_FUN" ADD CONSTRAINT "HAVING_FUN_CONCERT_FK" FOREIGN KEY ("CONCERT_ADDRESS", "CONCERT_DATETIME_START")
	  REFERENCES "BABUSAND"."CONCERT" ("PLACE_ADDRESS", "DATETIME_START") ENABLE;
 
  ALTER TABLE "BABUSAND"."HAVING_FUN" ADD CONSTRAINT "HAVING_FUN_FAN_FK" FOREIGN KEY ("FAN_FAN_ID")
	  REFERENCES "BABUSAND"."FAN" ("FAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IN_BAND
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."IN_BAND" ADD CONSTRAINT "IN_BAND_BAND_FK" FOREIGN KEY ("BAND_NAME")
	  REFERENCES "BABUSAND"."BAND" ("NAME") ENABLE;
 
  ALTER TABLE "BABUSAND"."IN_BAND" ADD CONSTRAINT "IN_BAND_MUSICIAN_FK" FOREIGN KEY ("MUSICIAN_FAN_ID")
	  REFERENCES "BABUSAND"."MUSICIAN" ("FAN_FAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IS_FAN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."IS_FAN" ADD CONSTRAINT "IS_FAN_BAND_FK" FOREIGN KEY ("BAND_NAME")
	  REFERENCES "BABUSAND"."BAND" ("NAME") ENABLE;
 
  ALTER TABLE "BABUSAND"."IS_FAN" ADD CONSTRAINT "IS_FAN_FAN_FK" FOREIGN KEY ("FAN_FAN_ID")
	  REFERENCES "BABUSAND"."FAN" ("FAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KEYBOARD
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."KEYBOARD" ADD CONSTRAINT "KEYBOARD_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MIC
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MIC" ADD CONSTRAINT "MIC_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUSICIAN
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MUSICIAN" ADD CONSTRAINT "MUSICIAN_FAN_FK" FOREIGN KEY ("FAN_FAN_ID")
	  REFERENCES "BABUSAND"."FAN" ("FAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUS_INST
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."MUS_INST" ADD CONSTRAINT "MUS_INST_MUSICIAN_FK" FOREIGN KEY ("MUSICIAN_FAN_ID")
	  REFERENCES "BABUSAND"."MUSICIAN" ("FAN_FAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OTHER
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."OTHER" ADD CONSTRAINT "OTHER_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERCUSSION
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."PERCUSSION" ADD CONSTRAINT "PERCUSSION_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFORMANCE
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."PERFORMANCE" ADD CONSTRAINT "PERFORMANCE_BAND_FK" FOREIGN KEY ("BAND_NAME")
	  REFERENCES "BABUSAND"."BAND" ("NAME") ENABLE;
 
  ALTER TABLE "BABUSAND"."PERFORMANCE" ADD CONSTRAINT "PERFORMANCE_CONCERT_FK" FOREIGN KEY ("CONCERT_ADDRESS", "CONCERT_DATETIME_START")
	  REFERENCES "BABUSAND"."CONCERT" ("PLACE_ADDRESS", "DATETIME_START") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SONG
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."SONG" ADD CONSTRAINT "SONG_BAND_FK" FOREIGN KEY ("BAND_NAME")
	  REFERENCES "BABUSAND"."BAND" ("NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STRINGED
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."STRINGED" ADD CONSTRAINT "STRINGED_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WIND
--------------------------------------------------------

  ALTER TABLE "BABUSAND"."WIND" ADD CONSTRAINT "WIND_MUS_INST_FK" FOREIGN KEY ("INSTRUMENT_INS_ID")
	  REFERENCES "BABUSAND"."MUS_INST" ("INSTRUMENT_INS_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_ELECTRONIC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_ELECTRONIC" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON ELECTRONIC FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'ELECTRONIC') THEN
      raise_application_error(-20223,'FK ELECTRONIC_MUS_INST_FK in Table ELECTRONIC violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''ELECTRONIC''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_ELECTRONIC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_KEYBOARD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_KEYBOARD" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON KEYBOARD FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'KEYBOARD') THEN
      raise_application_error(-20223,'FK KEYBOARD_MUS_INST_FK in Table KEYBOARD violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''KEYBOARD''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_KEYBOARD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_MIC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_MIC" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON MIC FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'MIC') THEN
      raise_application_error(-20223,'FK MIC_MUS_INST_FK in Table MIC violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''MIC''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_MIC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_OTHER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_OTHER" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON OTHER FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'OTHER') THEN
      raise_application_error(-20223,'FK OTHER_MUS_INST_FK in Table OTHER violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''OTHER''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_OTHER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_PERCUSSION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_PERCUSSION" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON PERCUSSION FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'PERCUSSION') THEN
      raise_application_error(-20223,'FK PERCUSSION_MUS_INST_FK in Table PERCUSSION violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''PERCUSSION''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_PERCUSSION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_STRINGED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_STRINGED" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON STRINGED FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'STRINGED') THEN
      raise_application_error(-20223,'FK STRINGED_MUS_INST_FK in Table STRINGED violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''STRINGED''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_STRINGED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_WIND
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BABUSAND"."ARC_FKARC_1_WIND" BEFORE
  INSERT OR
  UPDATE OF INSTRUMENT_INS_ID ON WIND FOR EACH ROW DECLARE d VARCHAR2 (15 CHAR);
  BEGIN
    SELECT A.INST_DESC_ID
    INTO d
    FROM MUS_INST A
    WHERE A.INSTRUMENT_INS_ID = :new.INSTRUMENT_INS_ID;
    IF (d                    IS NULL OR d <> 'WIND') THEN
      raise_application_error(-20223,'FK WIND_MUS_INST_FK in Table WIND violates Arc constraint on Table MUS_INST - discriminator column INST_DESC_ID doesn''t have value ''WIND''');
    END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END;
/
ALTER TRIGGER "BABUSAND"."ARC_FKARC_1_WIND" ENABLE;
--------------------------------------------------------
--  DDL for Function CHECKFANSARENOTMEMBERS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "BABUSAND"."CHECKFANSARENOTMEMBERS" RETURN NUMBER AS
  v_counter number;
BEGIN
SELECT COUNT(*) into v_counter FROM (
  SELECT * 
  FROM IS_FAN 
    INNER JOIN IN_BAND
    ON IS_FAN.BAND_NAME = IN_BAND.BAND_NAME
    AND IN_BAND.MUSICIAN_FAN_ID = IS_FAN.FAN_FAN_ID
    );

  IF (v_counter > 0)
    THEN 
      RETURN 0;
    ELSE 
      RETURN 1;
  END IF;
END CHECKFANSARENOTMEMBERS;

/